apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: getting-started-app-pvc
  labels:
    app: getting-started-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
  storageClassName: ebs-sc
  volumeMode: Filesystem
